// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyVersionAttribute("1.2.0")]
[assembly: AssemblyFileVersionAttribute("1.2.0")]
[assembly: AssemblyInformationalVersionAttribute("1.2.0")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyMetadataAttribute("githash","a7c900")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyVersion = "1.2.0";
        internal const System.String AssemblyFileVersion = "1.2.0";
        internal const System.String AssemblyInformationalVersion = "1.2.0";
        internal const System.Boolean ComVisible = false;
        internal const System.String AssemblyMetadata_githash = "a7c900";
    }
}
